Time::DATE_FORMATS[:day] = '%Y-%m-%d'
Time::DATE_FORMATS[:day_time]  = '%Y-%m-%d %H:%M:%S'
Time::DATE_FORMATS[:day_zh]  = '%Y年%m月%d日'
Time::DATE_FORMATS[:day_min_time]  = '%Y-%m-%d %H:%M'
Time::DATE_FORMATS[:day_time_zh]  = '%Y年%m月%d日 %H点%M分%S秒'
Time::DATE_FORMATS[:day_min_time_zh]  = '%Y年%m月%d日 %H点%M分'