# config/app.yml for rails-settings-cached
defaults: &defaults
  host: cms.com
  site_name: "cms"
  default_per_page: 20

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
